services:
  - type: web
    name: summerclass-project
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
